### ISSUE TITLE
Cannot have "Use SSL" off (struggling with alpha version)

### ISSUE THREAD

**Issue by michaelblight** [DeanCording/node-red-contrib-google-action#22]
It looks like the documentation currently covers the released version, but I'm trying to get the alpha version working. I have done the following:

- I already have a dynamic DNS provider and 8081 forwarded to the correct machine.
- Created a project on Actions on Google and gave it a name of "Michael's Test One".
- Put my URL in `action.json`. I'm not using SSL at the moment so I also changed it to "http".
- Installed `gactions` and ran the command from the documentation. I get the "michael-blight-test1 is now ready for testing" message.
- Once I do this I don't see any actions listed (ie. Default Welcome Intent) and if I use the Simulator I get "Michael's Test One isn't responding right now". I'm not sure if I should be able to do this now, so I press on.
- Pasted a `Start` node into NR and turned off "Use SSL". Once I deploy, the debug window shows "Error: ENOENT: no such file or directory, open ''" and the following appears in the log.

```
26 Jun 08:32:03 - [error] [action start:90878347.3e64d] Error: ENOENT: no such file or directory, open ''
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at new GoogleActionIn (/usr/src/node-red/node_modules/node-red-contrib-google-action/google-action.js:65:25)
    at Object.createNode (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/util.js:483:31)
    at Flow.start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:176:44)
    at start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:329:33)
    at stop.then.then (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:196:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

```
Line 65 of `google-action.js` is inside an if that should only execute if SSL is selected, not unselected.

**Comment by michaelblight** [comment]
BTW it's working properly with SSL, just not without.
